server:
  port: 8020
spring:
  application:
    name: menu
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orderingsystem?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: oneAPTX4869piece # TODO: password
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.example.entity
